// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/route.proto

package LogiLens

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OptimizationType int32

const (
	OptimizationType_DISTANCE OptimizationType = 0
	OptimizationType_TIME     OptimizationType = 1
	OptimizationType_COST     OptimizationType = 2
)

// Enum value maps for OptimizationType.
var (
	OptimizationType_name = map[int32]string{
		0: "DISTANCE",
		1: "TIME",
		2: "COST",
	}
	OptimizationType_value = map[string]int32{
		"DISTANCE": 0,
		"TIME":     1,
		"COST":     2,
	}
)

func (x OptimizationType) Enum() *OptimizationType {
	p := new(OptimizationType)
	*p = x
	return p
}

func (x OptimizationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OptimizationType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_route_proto_enumTypes[0].Descriptor()
}

func (OptimizationType) Type() protoreflect.EnumType {
	return &file_proto_route_proto_enumTypes[0]
}

func (x OptimizationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OptimizationType.Descriptor instead.
func (OptimizationType) EnumDescriptor() ([]byte, []int) {
	return file_proto_route_proto_rawDescGZIP(), []int{0}
}

type TransportMode int32

const (
	TransportMode_TRUCK TransportMode = 0
	TransportMode_AIR   TransportMode = 1
	TransportMode_RAIL  TransportMode = 2
	TransportMode_SHIP  TransportMode = 3
)

// Enum value maps for TransportMode.
var (
	TransportMode_name = map[int32]string{
		0: "TRUCK",
		1: "AIR",
		2: "RAIL",
		3: "SHIP",
	}
	TransportMode_value = map[string]int32{
		"TRUCK": 0,
		"AIR":   1,
		"RAIL":  2,
		"SHIP":  3,
	}
)

func (x TransportMode) Enum() *TransportMode {
	p := new(TransportMode)
	*p = x
	return p
}

func (x TransportMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransportMode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_route_proto_enumTypes[1].Descriptor()
}

func (TransportMode) Type() protoreflect.EnumType {
	return &file_proto_route_proto_enumTypes[1]
}

func (x TransportMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransportMode.Descriptor instead.
func (TransportMode) EnumDescriptor() ([]byte, []int) {
	return file_proto_route_proto_rawDescGZIP(), []int{1}
}

type RouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Destination   string                 `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	OptimizeBy    OptimizationType       `protobuf:"varint,3,opt,name=optimize_by,json=optimizeBy,proto3,enum=route.OptimizationType" json:"optimize_by,omitempty"`
	AllowedModes  []TransportMode        `protobuf:"varint,4,rep,packed,name=allowed_modes,json=allowedModes,proto3,enum=route.TransportMode" json:"allowed_modes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteRequest) Reset() {
	*x = RouteRequest{}
	mi := &file_proto_route_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteRequest) ProtoMessage() {}

func (x *RouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_route_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteRequest.ProtoReflect.Descriptor instead.
func (*RouteRequest) Descriptor() ([]byte, []int) {
	return file_proto_route_proto_rawDescGZIP(), []int{0}
}

func (x *RouteRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *RouteRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *RouteRequest) GetOptimizeBy() OptimizationType {
	if x != nil {
		return x.OptimizeBy
	}
	return OptimizationType_DISTANCE
}

func (x *RouteRequest) GetAllowedModes() []TransportMode {
	if x != nil {
		return x.AllowedModes
	}
	return nil
}

type RouteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RouteId       string                 `protobuf:"bytes,1,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	Steps         []*RouteStep           `protobuf:"bytes,2,rep,name=steps,proto3" json:"steps,omitempty"`
	TotalDistance float64                `protobuf:"fixed64,3,opt,name=total_distance,json=totalDistance,proto3" json:"total_distance,omitempty"`
	TotalTime     float64                `protobuf:"fixed64,4,opt,name=total_time,json=totalTime,proto3" json:"total_time,omitempty"`
	TotalCost     float64                `protobuf:"fixed64,5,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteResponse) Reset() {
	*x = RouteResponse{}
	mi := &file_proto_route_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteResponse) ProtoMessage() {}

func (x *RouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_route_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteResponse.ProtoReflect.Descriptor instead.
func (*RouteResponse) Descriptor() ([]byte, []int) {
	return file_proto_route_proto_rawDescGZIP(), []int{1}
}

func (x *RouteResponse) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *RouteResponse) GetSteps() []*RouteStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *RouteResponse) GetTotalDistance() float64 {
	if x != nil {
		return x.TotalDistance
	}
	return 0
}

func (x *RouteResponse) GetTotalTime() float64 {
	if x != nil {
		return x.TotalTime
	}
	return 0
}

func (x *RouteResponse) GetTotalCost() float64 {
	if x != nil {
		return x.TotalCost
	}
	return 0
}

type LatLng struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng           float64                `protobuf:"fixed64,2,opt,name=lng,proto3" json:"lng,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LatLng) Reset() {
	*x = LatLng{}
	mi := &file_proto_route_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatLng) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatLng) ProtoMessage() {}

func (x *LatLng) ProtoReflect() protoreflect.Message {
	mi := &file_proto_route_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatLng.ProtoReflect.Descriptor instead.
func (*LatLng) Descriptor() ([]byte, []int) {
	return file_proto_route_proto_rawDescGZIP(), []int{2}
}

func (x *LatLng) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *LatLng) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

type RouteStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Mode          TransportMode          `protobuf:"varint,3,opt,name=mode,proto3,enum=route.TransportMode" json:"mode,omitempty"`
	Distance      float64                `protobuf:"fixed64,4,opt,name=distance,proto3" json:"distance,omitempty"`
	Time          float64                `protobuf:"fixed64,5,opt,name=time,proto3" json:"time,omitempty"`
	Cost          float64                `protobuf:"fixed64,6,opt,name=cost,proto3" json:"cost,omitempty"`
	Geometry      []*LatLng              `protobuf:"bytes,7,rep,name=geometry,proto3" json:"geometry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteStep) Reset() {
	*x = RouteStep{}
	mi := &file_proto_route_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteStep) ProtoMessage() {}

func (x *RouteStep) ProtoReflect() protoreflect.Message {
	mi := &file_proto_route_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteStep.ProtoReflect.Descriptor instead.
func (*RouteStep) Descriptor() ([]byte, []int) {
	return file_proto_route_proto_rawDescGZIP(), []int{3}
}

func (x *RouteStep) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *RouteStep) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *RouteStep) GetMode() TransportMode {
	if x != nil {
		return x.Mode
	}
	return TransportMode_TRUCK
}

func (x *RouteStep) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *RouteStep) GetTime() float64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *RouteStep) GetCost() float64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *RouteStep) GetGeometry() []*LatLng {
	if x != nil {
		return x.Geometry
	}
	return nil
}

var File_proto_route_proto protoreflect.FileDescriptor

const file_proto_route_proto_rawDesc = "" +
	"\n" +
	"\x11proto/route.proto\x12\x05route\"\xbd\x01\n" +
	"\fRouteRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\x128\n" +
	"\voptimize_by\x18\x03 \x01(\x0e2\x17.route.OptimizationTypeR\n" +
	"optimizeBy\x129\n" +
	"\rallowed_modes\x18\x04 \x03(\x0e2\x14.route.TransportModeR\fallowedModes\"\xb7\x01\n" +
	"\rRouteResponse\x12\x19\n" +
	"\broute_id\x18\x01 \x01(\tR\arouteId\x12&\n" +
	"\x05steps\x18\x02 \x03(\v2\x10.route.RouteStepR\x05steps\x12%\n" +
	"\x0etotal_distance\x18\x03 \x01(\x01R\rtotalDistance\x12\x1d\n" +
	"\n" +
	"total_time\x18\x04 \x01(\x01R\ttotalTime\x12\x1d\n" +
	"\n" +
	"total_cost\x18\x05 \x01(\x01R\ttotalCost\",\n" +
	"\x06LatLng\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x02 \x01(\x01R\x03lng\"\xc8\x01\n" +
	"\tRouteStep\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12(\n" +
	"\x04mode\x18\x03 \x01(\x0e2\x14.route.TransportModeR\x04mode\x12\x1a\n" +
	"\bdistance\x18\x04 \x01(\x01R\bdistance\x12\x12\n" +
	"\x04time\x18\x05 \x01(\x01R\x04time\x12\x12\n" +
	"\x04cost\x18\x06 \x01(\x01R\x04cost\x12)\n" +
	"\bgeometry\x18\a \x03(\v2\r.route.LatLngR\bgeometry*4\n" +
	"\x10OptimizationType\x12\f\n" +
	"\bDISTANCE\x10\x00\x12\b\n" +
	"\x04TIME\x10\x01\x12\b\n" +
	"\x04COST\x10\x02*7\n" +
	"\rTransportMode\x12\t\n" +
	"\x05TRUCK\x10\x00\x12\a\n" +
	"\x03AIR\x10\x01\x12\b\n" +
	"\x04RAIL\x10\x02\x12\b\n" +
	"\x04SHIP\x10\x032I\n" +
	"\fRouteService\x129\n" +
	"\fComputeRoute\x12\x13.route.RouteRequest\x1a\x14.route.RouteResponseB Z\x1egithub.com/rudraa2005/LogiLensb\x06proto3"

var (
	file_proto_route_proto_rawDescOnce sync.Once
	file_proto_route_proto_rawDescData []byte
)

func file_proto_route_proto_rawDescGZIP() []byte {
	file_proto_route_proto_rawDescOnce.Do(func() {
		file_proto_route_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_route_proto_rawDesc), len(file_proto_route_proto_rawDesc)))
	})
	return file_proto_route_proto_rawDescData
}

var file_proto_route_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_route_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_route_proto_goTypes = []any{
	(OptimizationType)(0), // 0: route.OptimizationType
	(TransportMode)(0),    // 1: route.TransportMode
	(*RouteRequest)(nil),  // 2: route.RouteRequest
	(*RouteResponse)(nil), // 3: route.RouteResponse
	(*LatLng)(nil),        // 4: route.LatLng
	(*RouteStep)(nil),     // 5: route.RouteStep
}
var file_proto_route_proto_depIdxs = []int32{
	0, // 0: route.RouteRequest.optimize_by:type_name -> route.OptimizationType
	1, // 1: route.RouteRequest.allowed_modes:type_name -> route.TransportMode
	5, // 2: route.RouteResponse.steps:type_name -> route.RouteStep
	1, // 3: route.RouteStep.mode:type_name -> route.TransportMode
	4, // 4: route.RouteStep.geometry:type_name -> route.LatLng
	2, // 5: route.RouteService.ComputeRoute:input_type -> route.RouteRequest
	3, // 6: route.RouteService.ComputeRoute:output_type -> route.RouteResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_route_proto_init() }
func file_proto_route_proto_init() {
	if File_proto_route_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_route_proto_rawDesc), len(file_proto_route_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_route_proto_goTypes,
		DependencyIndexes: file_proto_route_proto_depIdxs,
		EnumInfos:         file_proto_route_proto_enumTypes,
		MessageInfos:      file_proto_route_proto_msgTypes,
	}.Build()
	File_proto_route_proto = out.File
	file_proto_route_proto_goTypes = nil
	file_proto_route_proto_depIdxs = nil
}
